### PR TITLE
documentation updated

### PR DESCRIPTION
**Pull request by chaanakyaaM**
User-friendly documentation is added, but there is a problem with sample CLI output image.

### CODE REVIEW

**Comment by Sl-Alex** [comment]
BTW, what is wrong with the image?

**Comment by chaanakyaaM** [comment]
I think the link of the image is broken.

**Review by chaanakyaaM — COMMENTED** [review]
nice

**Comment by chaanakyaaM** [comment]
oh, sorry, my bad.
Screenshot (100)
By seeing this, i thought the link was broken.

**Comment by chaanakyaaM** [comment]
Now the index.md is fully updated

**Comment by chaanakyaaM** [comment]
pleasure is mine.

**Comment by Sl-Alex** [comment]
@chaanakyaaM Do you still have problems with the image?
If yes, what browser/OS do you use?
It seems your browser (or maybe firewall) is blocking it.
It is just a small PNG file, you can check it manually [here](https://raw.githubusercontent.com/Sl-Alex/pyapitester/main/docs/cli_output.png)

In Windows and Android on the recent Chrome and Firefox it is rendered properly.

**Comment by Sl-Alex** [comment]
It seems to be some firewall problem on your side, GitHub servers normally don't return a timeout.
Could be some GitHub issue as well. Unfortunately, in both cases I can't help :(

**Comment by chaanakyaaM** [comment]
Its k, thank you.

**Pull request merged**
